[database]
url = "postgresql://postgres.ywwofrszjxpegkgpgxrs:dTP83nnGe25tE5Ej@aws-0-us-east-2.pooler.supabase.com:5432/postgres"

[supabase]
url = "https://ywwofrszjxpegkgpgxrs.supabase.co"
key = "sb_secret_n3aA-
x_G8UT4ynE28a0iow_PzN8tIfY"